import type { ProductVariantRef } from "@/src/domain/types";
import type { PriceChangeFixture } from "@/src/commerce/types";

const gid = (suffix: string) => `gid://shopify/ProductVariant/900000000000${suffix}`;
const productGid = (suffix: string) => `gid://shopify/Product/900000000000${suffix}`;

export const MOCK_DESK_PRODUCTS: readonly ProductVariantRef[] = [
  {
    merchandiseId: gid("01"),
    productId: productGid("01"),
    handle: "orange-desk-lamp",
    title: "Orange desk lamp",
    variantTitle: "Warm orange",
    role: "lamp",
    imageUrl: null,
    price: { amount: "39.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 20, depthCm: 18, heightCm: 38 },
    tags: ["cozy", "warm"],
  },
  {
    merchandiseId: gid("02"),
    productId: productGid("02"),
    handle: "paperframe-monitor",
    title: "Paperframe monitor",
    variantTitle: "24 inch sand",
    role: "display",
    imageUrl: null,
    price: { amount: "139.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 52, depthCm: 20, heightCm: 36 },
    tags: ["calm", "cozy"],
  },
  {
    merchandiseId: gid("03"),
    productId: productGid("03"),
    handle: "quiettype-keyboard",
    title: "QuietType keyboard",
    variantTitle: "Sandstone",
    role: "input",
    imageUrl: null,
    price: { amount: "49.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 39, depthCm: 14, heightCm: 4 },
    tags: ["quiet", "no-rgb"],
  },
  {
    merchandiseId: gid("04"),
    productId: productGid("04"),
    handle: "pebble-speaker",
    title: "Pebble speaker",
    variantTitle: "Moss",
    role: "audio",
    imageUrl: null,
    price: { amount: "39.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 18, depthCm: 16, heightCm: 18 },
    tags: ["calm"],
  },
  {
    merchandiseId: gid("05"),
    productId: productGid("05"),
    handle: "cork-desk-tray",
    title: "Cork desk tray",
    variantTitle: "Natural",
    role: "organization",
    imageUrl: null,
    price: { amount: "15.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 26, depthCm: 18, heightCm: 3 },
    tags: ["natural"],
  },
  {
    merchandiseId: gid("06"),
    productId: productGid("06"),
    handle: "terracotta-desk-plant",
    title: "Terracotta desk plant",
    variantTitle: "Small",
    role: "decor",
    imageUrl: null,
    price: { amount: "12.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 14, depthCm: 14, heightCm: 22 },
    tags: ["cozy", "natural"],
  },
  {
    merchandiseId: gid("07"),
    productId: productGid("07"),
    handle: "wide-studio-display",
    title: "Wide studio display",
    variantTitle: "32 inch",
    role: "display",
    imageUrl: null,
    price: { amount: "219.00", currencyCode: "USD" },
    available: false,
    market: "US",
    dimensions: { widthCm: 70, depthCm: 28, heightCm: 44 },
    tags: ["studio"],
  },
  {
    merchandiseId: gid("08"),
    productId: productGid("08"),
    handle: "walnut-headphone-stand",
    title: "Walnut headphone stand",
    variantTitle: "Dark walnut",
    role: "organization",
    imageUrl: null,
    price: { amount: "29.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 18, depthCm: 18, heightCm: 28 },
    tags: ["warm"],
  },
  {
    merchandiseId: gid("09"),
    productId: productGid("09"),
    handle: "partial-failure-fixture",
    title: "Partial failure fixture",
    variantTitle: "Test only",
    role: "decor",
    imageUrl: null,
    price: { amount: "5.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 10, depthCm: 10, heightCm: 10 },
    tags: ["fixture"],
  },
  {
    merchandiseId: gid("10"),
    productId: productGid("10"),
    handle: "felt-catchall-coaster",
    title: "Felt catchall coaster",
    variantTitle: "Moss",
    role: "decor",
    imageUrl: null,
    price: { amount: "9.00", currencyCode: "USD" },
    available: true,
    market: "US",
    dimensions: { widthCm: 16, depthCm: 16, heightCm: 2 },
    tags: ["calm", "compact"],
  },
] as const;

export const MOCK_UNAVAILABLE_MERCHANDISE_ID = gid("07");
export const MOCK_PARTIAL_FAILURE_MERCHANDISE_ID = gid("09");
export const MOCK_PRICE_CHANGE: PriceChangeFixture = {
  merchandiseId: gid("04"),
  previousPrice: { amount: "35.00", currencyCode: "USD" },
  currentPrice: { amount: "39.00", currencyCode: "USD" },
};
